project_id = "dfgbtsbmgojysixiqnll"

[functions.analyze-food]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.create-first-admin]
verify_jwt = false

[functions.send-email-gmail]
verify_jwt = true