import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "sv" | "fr" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // StartPage
    "start.welcome": "Welcome to CarbSmart!",
    "start.description": "Take photos of meals and get instant carb estimates to help manage your child's diabetes",
    "start.getStarted": "Get Started",
    "start.selectLanguage": "Select Language",
    "start.disclaimerTitle": "Important Disclaimer",
    "start.disclaimerText": "This app uses AI to estimate the carbohydrate content of food from images. Results are only estimates and may be inaccurate depending on how photos are taken.\n\nAlways use this tool with care — you should understand the basics of carbohydrate counting and insulin calculation before use.\n\nThe app and its creators do not take responsibility for any medical or dietary decisions based on these results. Always confirm with a healthcare professional when in doubt.",
    "start.accept": "I Understand and Accept",
    "start.decline": "Decline",
    
    // Main App
    "app.title": "CarbSmart",
    "app.subtitle": "your carb counter",
    "app.analyzing": "Analyzing...",
    "app.analyzingDesc": "AI is examining your food photo",
    "app.analysisComplete": "Analysis Complete!",
    "app.analysisCompleteDesc": "Found {carbs}g carbs, suggesting {insulin} units of insulin",
    "app.savedToHistory": "Saved to History",
    "app.savedToHistoryDesc": "Your meal has been saved successfully",
    "app.error": "Error",
    "app.errorDesc": "Failed to analyze image. Please try again.",
    
    // Tabs
    "tabs.capture": "Capture",
    "tabs.meals": "Meals",
    "tabs.history": "History",
    "tabs.info": "Info",
    "tabs.settings": "Settings",
    
    // Auth
    "auth.welcome": "Welcome to CarbSmart",
    "auth.welcomeDesc": "Sign in or create an account to continue",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.admin": "Admin",
    "auth.adminSignIn": "Admin Sign In",
    "auth.notAdmin": "You do not have admin privileges",
    "auth.email": "Email",
    "auth.password": "Password (min 6 characters)",
    "auth.loading": "Loading...",
    "auth.signupSuccess": "Account created",
    "auth.signupSuccessDesc": "You can now sign in with your credentials",
    "auth.signOut": "Sign Out",
    "auth.forgotPassword": "Forgot Password?",
    "auth.resetPassword": "Reset Password",
    "auth.sendResetLink": "Send Reset Link",
    "auth.resetEmailSent": "Reset Email Sent",
    "auth.checkEmail": "Check your email for a password reset link",
    "auth.sending": "Sending...",
    "auth.cancel": "Cancel",
    "auth.accountPending": "Account Pending Approval",
    "auth.accountPendingDesc": "Your account is waiting for admin approval",
    "auth.accountDeclined": "Account Declined",
    "auth.accountDeclinedDesc": "Your account has been declined by an admin",
    "auth.profileError": "Could not verify account status",
    
    // Camera
    "camera.title": "Capture Food",
    "camera.takePhoto": "Take Photo",
    "camera.retake": "Retake",
    "camera.analyze": "Analyze",
    "camera.error": "Camera Error",
    "camera.errorDesc": "Could not access camera. Please check permissions.",
    
    // Results
    "results.title": "Results",
    "results.estimatedCarbs": "Estimated Carbs",
    "results.totalCarbs": "Total Carbs",
    "results.recommendedInsulin": "Recommended Insulin Dose",
    "results.insulinNeeded": "Insulin Needed",
    "results.grams": "grams",
    "results.units": "units",
    "results.carbs": "Carbs",
    "results.basedOnRatio": "Based on 1:{ratio} ratio",
    "results.fromPhotos": "from {count} photos",
    "results.addMore": "More Pictures",
    "results.done": "Done - Calculate & Save",
    "results.abort": "Abort",
    "results.viewHistory": "View History",
    "results.newPhoto": "New Photo",
    
    // History
    "history.title": "Recent Calculations",
    "history.noHistory": "No history yet. Start by taking a photo!",
    "history.meals": "meal",
    "history.mealsPlural": "meals",
    "history.carbs": "carbs",
    "history.insulin": "insulin",
    "history.insulinNeeded": "insulin needed",
    "history.today": "Today",
    
    // Settings
    "settings.title": "Your Settings",
    "settings.setupPin": "Set Up Parental Control",
    "settings.setupPinDesc": "Create a 4-digit PIN to protect your settings",
    "settings.enterPin": "Enter PIN",
    "settings.confirmPin": "Confirm PIN",
    "settings.setPin": "Set PIN",
    "settings.unlockSettings": "Enter PIN to Access Settings",
    "settings.parentalControl": "Parental control is enabled",
    "settings.unlock": "Unlock Settings",
    "settings.settingsUnlocked": "Settings Unlocked",
    "settings.lockSettings": "Lock Settings",
    "settings.insulinRatio": "Insulin-to-Carb Ratio (I:C)",
    "settings.insulinRatioDesc": "1 unit of insulin covers {ratio} grams of carbs",
    "settings.portionSize": "Portion Size",
    "settings.portionSizeDesc": "Select typical portion size for carb estimation",
    "settings.childPortion": "Child Portion",
    "settings.adultPortion": "Adult Portion",
    "settings.comments": "Comments / Notes",
    "settings.commentsPlaceholder": "Add any notes or comments about your diabetes management...",
    "settings.commentsDesc": "Use this space for reminders, doctor notes, or other important information",
    "settings.invalidPin": "Invalid PIN",
    "settings.invalidPinDesc": "PIN must be exactly 4 digits",
    "settings.pinMismatch": "PINs don't match",
    "settings.pinMismatchDesc": "Please make sure both PINs match",
    "settings.pinSuccess": "PIN Set Successfully",
    "settings.pinSuccessDesc": "Your parental control PIN has been created",
    "settings.accessGranted": "Access Granted",
    "settings.accessGrantedDesc": "Welcome to Settings",
    "settings.incorrectPin": "Incorrect PIN",
    "settings.incorrectPinDesc": "Please try again",
    "settings.rereadDisclaimer": "Re-read Disclaimer",
    
    // Meal Examples
    "meals.title": "Kid-Friendly Meal Examples",
    "meals.subtitle": "Common meals with estimated carb counts",
    "meals.breakfast": "Breakfast",
    "meals.lunch": "Lunch",
    "meals.dinner": "Dinner",
    "meals.supper": "Supper",
    "meals.disclaimer": "💡 These are estimates. Always verify with nutrition labels when possible.",
    "meals.insulinEstimate": "~{insulin}u insulin",
    
    // Meal names
    "meal.pancakes": "Pancakes with syrup",
    "meal.pancakesDesc": "2 medium pancakes with 2 tbsp syrup",
    "meal.cereal": "Cereal with milk",
    "meal.cerealDesc": "1 cup cereal with 1/2 cup milk",
    "meal.toast": "Toast with jam",
    "meal.toastDesc": "2 slices toast with 1 tbsp jam",
    "meal.oatmeal": "Oatmeal with banana",
    "meal.oatmealDesc": "1 cup oatmeal with 1 small banana",
    "meal.waffles": "Waffles with fruit",
    "meal.wafflesDesc": "2 waffles with 1/2 cup berries",
    "meal.bagel": "Bagel with cream cheese",
    "meal.bagelDesc": "1 small bagel with 2 tbsp cream cheese",
    "meal.pbSandwich": "Peanut butter sandwich",
    "meal.pbSandwichDesc": "2 slices bread with 2 tbsp PB",
    "meal.macCheese": "Mac and cheese",
    "meal.macCheeseDesc": "1 cup prepared mac and cheese",
    "meal.nuggets": "Chicken nuggets meal",
    "meal.nuggetsDesc": "6 nuggets with small fries",
    "meal.grilledCheese": "Grilled cheese",
    "meal.grilledCheeseDesc": "2 slices bread with cheese",
    "meal.pizza": "Pizza slice",
    "meal.pizzaDesc": "1 slice cheese pizza",
    "meal.turkeyWrap": "Turkey wrap",
    "meal.turkeyWrapDesc": "1 tortilla with turkey and veggies",
    "meal.roastChicken": "Roast chicken with veggies",
    "meal.roastChickenDesc": "Baked chicken with roasted vegetables and small potato",
    "meal.meatloaf": "Meatloaf with sides",
    "meal.meatloafDesc": "Meatloaf slice with green beans and mashed potatoes",
    "meal.stirFry": "Beef stir fry",
    "meal.stirFryDesc": "Beef stir fry with vegetables over rice",
    "meal.salmon": "Baked salmon dinner",
    "meal.salmonDesc": "Salmon fillet with broccoli and rice",
    "meal.chickenParm": "Chicken parmesan",
    "meal.chickenParmDesc": "Breaded chicken with melted cheese over spaghetti",
    "meal.porkChop": "Pork chop dinner",
    "meal.porkChopDesc": "Grilled pork chop with applesauce and corn",
    "meal.spaghetti": "Spaghetti with meatballs",
    "meal.spaghettiDesc": "1 cup pasta with 3 meatballs",
    "meal.chickenRice": "Chicken with rice",
    "meal.chickenRiceDesc": "4 oz chicken with 3/4 cup rice",
    "meal.tacos": "Tacos",
    "meal.tacosDesc": "2 soft tacos with meat and toppings",
    "meal.fishSticks": "Fish sticks meal",
    "meal.fishSticksDesc": "5 fish sticks with mashed potatoes",
    "meal.hamburger": "Hamburger with bun",
    "meal.hamburgerDesc": "1 burger with bun and small side",
    "meal.quesadilla": "Chicken quesadilla",
    "meal.quesadillaDesc": "1 quesadilla with cheese and chicken",
    
    // Admin
    "admin.title": "Admin Dashboard",
    "admin.backToApp": "Back to App",
    "admin.inviteUser": "Invite New User",
    "admin.email": "Email",
    "admin.temporaryPassword": "Temporary Password",
    "admin.fullName": "Full Name (Optional)",
    "admin.minCharacters": "Min 6 characters",
    "admin.creating": "Creating...",
    "admin.createAccount": "Create User Account",
    "admin.users": "Users",
    "admin.name": "Name",
    "admin.role": "Role",
    "admin.created": "Created",
    "admin.actions": "Actions",
    "admin.removeAdmin": "Remove Admin",
    "admin.makeAdmin": "Make Admin",
    "admin.deleteUser": "Delete User",
    "admin.deleteConfirm": "Are you sure you want to delete this user? This action cannot be undone.",
    "admin.cancel": "Cancel",
    "admin.delete": "Delete",
    "admin.userCreated": "User Created",
    "admin.successInvite": "Successfully invited {email}",
    "admin.userDeleted": "User Deleted",
    "admin.userRemoved": "User has been removed",
    "admin.adminRoleRemoved": "Admin role removed",
    "admin.adminRoleGranted": "Admin role granted",
    "admin.accessDenied": "Access Denied",
    "admin.noPermissions": "You don't have admin permissions",
    "admin.loading": "Loading...",
    "admin.status": "Status",
    "admin.approve": "Approve",
    "admin.decline": "Decline",
    "admin.userApproved": "User Approved",
    "admin.userCanLogin": "User can now log in to the app",
    "admin.userDeclined": "User Declined",
    "admin.userDenied": "User access has been denied",
    "admin.membershipApplications": "Membership Applications",
    "admin.pending": "Pending",
    "admin.noPendingApplications": "No pending applications",
    "admin.applicationMessage": "Application Message:",
    "admin.reject": "Reject",
    
    // Admin Statistics
    "admin.statistics": "Statistics",
    "admin.totalUsers": "Total Users",
    "admin.appStarts": "App Starts",
    "admin.newUsers30Days": "New Users (30 days)",
    "admin.userGrowth": "User Growth (Last 30 Days)",
    "admin.applicationApproved": "Application Approved",
    "admin.applicationApprovedDesc": "User account created and email sent.",
    "admin.applicationRejected": "Application Rejected",
    "admin.applicationRejectedDesc": "The application has been rejected.",
    "admin.resetEmailSent": "Reset Email Sent",
    "admin.resetEmailSentDesc": "Password reset email sent to {email}",
    
    // Membership Application
    "application.title": "Apply for Membership",
    "application.description": "Fill out the form below to apply for membership. You will receive an email confirmation once submitted.",
    "application.email": "Email",
    "application.whyJoin": "Why do you want to join?",
    "application.whyJoinPlaceholder": "Tell us a bit about yourself and why you'd like to become a member...",
    "application.cancel": "Cancel",
    "application.submit": "Submit Application",
    "application.submitting": "Submitting...",
    "application.noAccount": "Don't have an account yet?",
    
    // NotFound
    "notFound.title": "404",
    "notFound.message": "Oops! Page not found",
    "notFound.returnHome": "Return to Home",
  },
  sv: {
    // StartPage
    "start.welcome": "Välkommen till CarbSmart!",
    "start.description": "Ta bilder på måltider och få omedelbar uppskattning av kolhydrater för att hjälpa till att hantera ditt barns diabetes",
    "start.getStarted": "Kom igång",
    "start.selectLanguage": "Välj språk",
    "start.disclaimerTitle": "Viktig ansvarsfriskrivning",
    "start.disclaimerText": "Denna app använder AI för att uppskatta kolhydratinnehållet i mat från bilder. Resultaten är endast uppskattningar och kan vara felaktiga beroende på hur fotona tas.\n\nAnvänd alltid detta verktyg med försiktighet — du bör förstå grunderna för kolhydraträkning och insulinberäkning innan användning.\n\nAppen och dess skapare tar inget ansvar för medicinska eller kostmässiga beslut baserade på dessa resultat. Bekräfta alltid med en vårdpersonal vid tveksamhet.",
    "start.accept": "Jag förstår och accepterar",
    "start.decline": "Avböj",
    
    // Main App
    "app.title": "CarbSmart",
    "app.subtitle": "din kolhydratmätare",
    "app.analyzing": "Analyserar...",
    "app.analyzingDesc": "AI undersöker din matbild",
    "app.analysisComplete": "Analys klar!",
    "app.analysisCompleteDesc": "Hittade {carbs}g kolhydrater, föreslår {insulin} enheter insulin",
    "app.savedToHistory": "Sparat till historik",
    "app.savedToHistoryDesc": "Din måltid har sparats framgångsrikt",
    "app.error": "Fel",
    "app.errorDesc": "Misslyckades med att analysera bilden. Försök igen.",
    
    // Tabs
    "tabs.capture": "Fånga",
    "tabs.meals": "Måltider",
    "tabs.history": "Historik",
    "tabs.info": "Info",
    "tabs.settings": "Inställningar",
    
    // Auth
    "auth.welcome": "Välkommen till CarbSmart",
    "auth.welcomeDesc": "Logga in eller skapa ett konto för att fortsätta",
    "auth.signIn": "Logga in",
    "auth.signUp": "Registrera",
    "auth.admin": "Admin",
    "auth.adminSignIn": "Admin-inloggning",
    "auth.notAdmin": "Du har inte adminbehörighet",
    "auth.email": "E-post",
    "auth.password": "Lösenord (minst 6 tecken)",
    "auth.loading": "Laddar...",
    "auth.signupSuccess": "Konto skapat",
    "auth.signupSuccessDesc": "Du kan nu logga in med dina uppgifter",
    "auth.signOut": "Logga ut",
    "auth.forgotPassword": "Glömt lösenord?",
    "auth.resetPassword": "Återställ lösenord",
    "auth.sendResetLink": "Skicka återställningslänk",
    "auth.resetEmailSent": "Återställningsmail skickat",
    "auth.checkEmail": "Kontrollera din e-post för länk till lösenordsåterställning",
    "auth.sending": "Skickar...",
    "auth.cancel": "Avbryt",
    "auth.accountPending": "Konto väntar på godkännande",
    "auth.accountPendingDesc": "Ditt konto väntar på godkännande från admin",
    "auth.accountDeclined": "Konto nekat",
    "auth.accountDeclinedDesc": "Ditt konto har nekats av en admin",
    "auth.profileError": "Kunde inte verifiera kontostatus",
    
    // Camera
    "camera.title": "Fånga mat",
    "camera.takePhoto": "Ta foto",
    "camera.retake": "Ta om",
    "camera.analyze": "Analysera",
    "camera.error": "Kamerafel",
    "camera.errorDesc": "Kunde inte komma åt kameran. Kontrollera behörigheter.",
    
    // Results
    "results.title": "Resultat",
    "results.estimatedCarbs": "Uppskattade kolhydrater",
    "results.totalCarbs": "Totalt kolhydrater",
    "results.recommendedInsulin": "Rekommenderad insulindos",
    "results.insulinNeeded": "Insulin som behövs",
    "results.grams": "gram",
    "results.units": "enheter",
    "results.carbs": "Kolhydrater",
    "results.basedOnRatio": "Baserat på 1:{ratio} förhållande",
    "results.fromPhotos": "från {count} foton",
    "results.addMore": "Fler bilder",
    "results.done": "Klar - Beräkna & Spara",
    "results.abort": "Avbryt",
    "results.viewHistory": "Visa historik",
    "results.newPhoto": "Nytt foto",
    
    // History
    "history.title": "Senaste beräkningar",
    "history.noHistory": "Ingen historik ännu. Börja med att ta ett foto!",
    "history.meals": "måltid",
    "history.mealsPlural": "måltider",
    "history.carbs": "kolhydrater",
    "history.insulin": "insulin",
    "history.insulinNeeded": "insulin behövs",
    "history.today": "Idag",
    
    // Settings
    "settings.title": "Dina inställningar",
    "settings.setupPin": "Ställ in föräldrakontroll",
    "settings.setupPinDesc": "Skapa en 4-siffrig PIN-kod för att skydda dina inställningar",
    "settings.enterPin": "Ange PIN",
    "settings.confirmPin": "Bekräfta PIN",
    "settings.setPin": "Ställ in PIN",
    "settings.unlockSettings": "Ange PIN för att komma åt inställningar",
    "settings.parentalControl": "Föräldrakontroll är aktiverad",
    "settings.unlock": "Lås upp inställningar",
    "settings.settingsUnlocked": "Inställningar upplåsta",
    "settings.lockSettings": "Lås inställningar",
    "settings.insulinRatio": "Insulin-till-kolhydrat-förhållande (I:C)",
    "settings.insulinRatioDesc": "1 enhet insulin täcker {ratio} gram kolhydrater",
    "settings.portionSize": "Portionsstorlek",
    "settings.portionSizeDesc": "Välj typisk portionsstorlek för kolhydratberäkning",
    "settings.childPortion": "Barnportion",
    "settings.adultPortion": "Vuxenportion",
    "settings.comments": "Kommentarer / Anteckningar",
    "settings.commentsPlaceholder": "Lägg till anteckningar eller kommentarer om din diabeteshantering...",
    "settings.commentsDesc": "Använd detta utrymme för påminnelser, läkaranteckningar eller annan viktig information",
    "settings.invalidPin": "Ogiltig PIN",
    "settings.invalidPinDesc": "PIN måste vara exakt 4 siffror",
    "settings.pinMismatch": "PIN-koderna matchar inte",
    "settings.pinMismatchDesc": "Se till att båda PIN-koderna matchar",
    "settings.pinSuccess": "PIN inställd",
    "settings.pinSuccessDesc": "Din föräldrakontroll PIN har skapats",
    "settings.accessGranted": "Åtkomst beviljad",
    "settings.accessGrantedDesc": "Välkommen till inställningar",
    "settings.incorrectPin": "Felaktig PIN",
    "settings.incorrectPinDesc": "Försök igen",
    "settings.rereadDisclaimer": "Läs ansvarsfriskrivning igen",
    
    // Meal Examples
    "meals.title": "Barnvänliga måltidsexempel",
    "meals.subtitle": "Vanliga måltider med uppskattade kolhydrater",
    "meals.breakfast": "Frukost",
    "meals.lunch": "Lunch",
    "meals.dinner": "Middag",
    "meals.supper": "Kvällsmat",
    "meals.disclaimer": "💡 Dessa är uppskattningar. Verifiera alltid med näringsdeklarationer när det är möjligt.",
    "meals.insulinEstimate": "~{insulin}e insulin",
    
    // Meal names
    "meal.pancakes": "Pannkakor med sirap",
    "meal.pancakesDesc": "2 medelstora pannkakor med 2 msk sirap",
    "meal.cereal": "Flingor med mjölk",
    "meal.cerealDesc": "1 kopp flingor med 1/2 kopp mjölk",
    "meal.toast": "Rostat bröd med sylt",
    "meal.toastDesc": "2 skivor rostat bröd med 1 msk sylt",
    "meal.oatmeal": "Havregrynsgröt med banan",
    "meal.oatmealDesc": "1 kopp havregrynsgröt med 1 liten banan",
    "meal.waffles": "Våfflor med frukt",
    "meal.wafflesDesc": "2 våfflor med 1/2 kopp bär",
    "meal.bagel": "Bagel med färskost",
    "meal.bagelDesc": "1 liten bagel med 2 msk färskost",
    "meal.pbSandwich": "Jordnötssmörsmacka",
    "meal.pbSandwichDesc": "2 skivor bröd med 2 msk jordnötssmör",
    "meal.macCheese": "Makaroner och ost",
    "meal.macCheeseDesc": "1 kopp tillagade makaroner och ost",
    "meal.nuggets": "Kycklingnuggets måltid",
    "meal.nuggetsDesc": "6 nuggets med små pommes",
    "meal.grilledCheese": "Grillad ostsmörgås",
    "meal.grilledCheeseDesc": "2 skivor bröd med ost",
    "meal.pizza": "Pizzabit",
    "meal.pizzaDesc": "1 bit ostpizza",
    "meal.turkeyWrap": "Kalkonwrap",
    "meal.turkeyWrapDesc": "1 tortilla med kalkon och grönsaker",
    "meal.roastChicken": "Rostad kyckling med grönsaker",
    "meal.roastChickenDesc": "Bakad kyckling med rostade grönsaker och liten potatis",
    "meal.meatloaf": "Köttfärslimpa med tillbehör",
    "meal.meatloafDesc": "Köttfärslimpskiva med gröna bönor och potatismos",
    "meal.stirFry": "Biff wok",
    "meal.stirFryDesc": "Biff wok med grönsaker över ris",
    "meal.salmon": "Bakad lax middag",
    "meal.salmonDesc": "Laxfilé med broccoli och ris",
    "meal.chickenParm": "Kycklingparmigiana",
    "meal.chickenParmDesc": "Panerad kyckling med smält ost över spaghetti",
    "meal.porkChop": "Fläskkotlett middag",
    "meal.porkChopDesc": "Grillad fläskkotlett med äppelmos och majs",
    "meal.spaghetti": "Spaghetti med köttbullar",
    "meal.spaghettiDesc": "1 kopp pasta med 3 köttbullar",
    "meal.chickenRice": "Kyckling med ris",
    "meal.chickenRiceDesc": "115g kyckling med 3/4 kopp ris",
    "meal.tacos": "Tacos",
    "meal.tacosDesc": "2 mjuka tacos med kött och pålägg",
    "meal.fishSticks": "Fiskpinnar måltid",
    "meal.fishSticksDesc": "5 fiskpinnar med potatismos",
    "meal.hamburger": "Hamburgare med bröd",
    "meal.hamburgerDesc": "1 burgare med bröd och liten tillbehör",
    "meal.quesadilla": "Kycklingquesadilla",
    "meal.quesadillaDesc": "1 quesadilla med ost och kyckling",
    
    // Admin
    "admin.title": "Admin-instrumentpanel",
    "admin.backToApp": "Tillbaka till appen",
    "admin.inviteUser": "Bjud in ny användare",
    "admin.email": "E-post",
    "admin.temporaryPassword": "Tillfälligt lösenord",
    "admin.fullName": "Fullständigt namn (valfritt)",
    "admin.minCharacters": "Minst 6 tecken",
    "admin.creating": "Skapar...",
    "admin.createAccount": "Skapa användarkonto",
    "admin.users": "Användare",
    "admin.name": "Namn",
    "admin.role": "Roll",
    "admin.created": "Skapad",
    "admin.actions": "Åtgärder",
    "admin.removeAdmin": "Ta bort admin",
    "admin.makeAdmin": "Gör till admin",
    "admin.deleteUser": "Ta bort användare",
    "admin.deleteConfirm": "Är du säker på att du vill ta bort denna användare? Denna åtgärd kan inte ångras.",
    "admin.cancel": "Avbryt",
    "admin.delete": "Ta bort",
    "admin.userCreated": "Användare skapad",
    "admin.successInvite": "Bjöd in {email}",
    "admin.userDeleted": "Användare borttagen",
    "admin.userRemoved": "Användaren har tagits bort",
    "admin.adminRoleRemoved": "Admin-roll borttagen",
    "admin.adminRoleGranted": "Admin-roll beviljad",
    "admin.accessDenied": "Åtkomst nekad",
    "admin.noPermissions": "Du har inte adminbehörigheter",
    "admin.loading": "Laddar...",
    "admin.status": "Status",
    "admin.approve": "Godkänn",
    "admin.decline": "Neka",
    "admin.userApproved": "Användare godkänd",
    "admin.userCanLogin": "Användaren kan nu logga in i appen",
    "admin.userDeclined": "Användare nekad",
    "admin.userDenied": "Användaråtkomst har nekats",
    "admin.membershipApplications": "Medlemsansökningar",
    "admin.pending": "Väntande",
    "admin.noPendingApplications": "Inga väntande ansökningar",
    "admin.applicationMessage": "Ansökningsmeddelande:",
    "admin.reject": "Avvisa",
    
    // Admin Statistics
    "admin.statistics": "Statistik",
    "admin.totalUsers": "Totalt antal användare",
    "admin.appStarts": "App-starter",
    "admin.newUsers30Days": "Nya användare (30 dagar)",
    "admin.userGrowth": "Användartillväxt (Senaste 30 dagarna)",
    "admin.applicationApproved": "Ansökan godkänd",
    "admin.applicationApprovedDesc": "Användarkonto skapat och e-post skickat.",
    "admin.applicationRejected": "Ansökan avvisad",
    "admin.applicationRejectedDesc": "Ansökan har avvisats.",
    "admin.resetEmailSent": "Återställningsmail skickat",
    "admin.resetEmailSentDesc": "Återställningsmail för lösenord skickat till {email}",
    
    // Membership Application
    "application.title": "Ansök om medlemskap",
    "application.description": "Fyll i formuläret nedan för att ansöka om medlemskap. Du kommer att få en e-postbekräftelse när det är inskickat.",
    "application.email": "E-post",
    "application.whyJoin": "Varför vill du gå med?",
    "application.whyJoinPlaceholder": "Berätta lite om dig själv och varför du vill bli medlem...",
    "application.cancel": "Avbryt",
    "application.submit": "Skicka ansökan",
    "application.submitting": "Skickar...",
    "application.noAccount": "Har du inget konto ännu?",
    
    // NotFound
    "notFound.title": "404",
    "notFound.message": "Hoppsan! Sidan hittades inte",
    "notFound.returnHome": "Tillbaka till startsidan",
  },
  fr: {
    // StartPage
    "start.welcome": "Bienvenue sur CarbSmart!",
    "start.description": "Prenez des photos de repas et obtenez des estimations instantanées de glucides pour aider à gérer le diabète de votre enfant",
    "start.getStarted": "Commencer",
    "start.selectLanguage": "Sélectionner la langue",
    "start.disclaimerTitle": "Avertissement important",
    "start.disclaimerText": "Cette application utilise l'IA pour estimer la teneur en glucides des aliments à partir d'images. Les résultats ne sont que des estimations et peuvent être inexacts selon la façon dont les photos sont prises.\n\nUtilisez toujours cet outil avec prudence - vous devez comprendre les bases du comptage des glucides et du calcul de l'insuline avant utilisation.\n\nL'application et ses créateurs n'assument aucune responsabilité pour les décisions médicales ou diététiques basées sur ces résultats. Confirmez toujours avec un professionnel de la santé en cas de doute.",
    "start.accept": "Je comprends et j'accepte",
    "start.decline": "Refuser",
    
    // Main App
    "app.title": "CarbSmart",
    "app.subtitle": "votre compteur de glucides",
    "app.analyzing": "Analyse en cours...",
    "app.analyzingDesc": "L'IA examine votre photo de nourriture",
    "app.analysisComplete": "Analyse terminée!",
    "app.analysisCompleteDesc": "Trouvé {carbs}g de glucides, suggérant {insulin} unités d'insuline",
    "app.savedToHistory": "Enregistré dans l'historique",
    "app.savedToHistoryDesc": "Votre repas a été enregistré avec succès",
    "app.error": "Erreur",
    "app.errorDesc": "Échec de l'analyse de l'image. Veuillez réessayer.",
    
    // Tabs
    "tabs.capture": "Capturer",
    "tabs.meals": "Repas",
    "tabs.history": "Historique",
    "tabs.info": "Info",
    "tabs.settings": "Paramètres",
    
    // Auth
    "auth.welcome": "Bienvenue sur CarbSmart",
    "auth.welcomeDesc": "Connectez-vous ou créez un compte pour continuer",
    "auth.signIn": "Se connecter",
    "auth.signUp": "S'inscrire",
    "auth.admin": "Admin",
    "auth.adminSignIn": "Connexion Admin",
    "auth.notAdmin": "Vous n'avez pas les privilèges d'admin",
    "auth.email": "Email",
    "auth.password": "Mot de passe (min 6 caractères)",
    "auth.loading": "Chargement...",
    "auth.signupSuccess": "Compte créé",
    "auth.signupSuccessDesc": "Vous pouvez maintenant vous connecter avec vos identifiants",
    "auth.signOut": "Se déconnecter",
    "auth.forgotPassword": "Mot de passe oublié?",
    "auth.resetPassword": "Réinitialiser le mot de passe",
    "auth.sendResetLink": "Envoyer le lien de réinitialisation",
    "auth.resetEmailSent": "Email de réinitialisation envoyé",
    "auth.checkEmail": "Vérifiez votre email pour le lien de réinitialisation du mot de passe",
    "auth.sending": "Envoi...",
    "auth.cancel": "Annuler",
    "auth.accountPending": "Compte en attente d'approbation",
    "auth.accountPendingDesc": "Votre compte attend l'approbation de l'admin",
    "auth.accountDeclined": "Compte refusé",
    "auth.accountDeclinedDesc": "Votre compte a été refusé par un admin",
    "auth.profileError": "Impossible de vérifier le statut du compte",
    
    // Camera
    "camera.title": "Capturer la nourriture",
    "camera.takePhoto": "Prendre une photo",
    "camera.retake": "Reprendre",
    "camera.analyze": "Analyser",
    "camera.error": "Erreur de caméra",
    "camera.errorDesc": "Impossible d'accéder à la caméra. Veuillez vérifier les permissions.",
    
    // Results
    "results.title": "Résultats",
    "results.estimatedCarbs": "Glucides estimés",
    "results.totalCarbs": "Total de glucides",
    "results.recommendedInsulin": "Dose d'insuline recommandée",
    "results.insulinNeeded": "Insuline nécessaire",
    "results.grams": "grammes",
    "results.units": "unités",
    "results.carbs": "Glucides",
    "results.basedOnRatio": "Basé sur un ratio 1:{ratio}",
    "results.fromPhotos": "de {count} photos",
    "results.addMore": "Plus de photos",
    "results.done": "Terminé - Calculer et enregistrer",
    "results.abort": "Annuler",
    "results.viewHistory": "Voir l'historique",
    "results.newPhoto": "Nouvelle photo",
    
    // History
    "history.title": "Calculs récents",
    "history.noHistory": "Pas encore d'historique. Commencez par prendre une photo!",
    "history.meals": "repas",
    "history.mealsPlural": "repas",
    "history.carbs": "glucides",
    "history.insulin": "insuline",
    "history.insulinNeeded": "insuline nécessaire",
    "history.today": "Aujourd'hui",
    
    // Settings
    "settings.title": "Vos paramètres",
    "settings.setupPin": "Configurer le contrôle parental",
    "settings.setupPinDesc": "Créez un code PIN à 4 chiffres pour protéger vos paramètres",
    "settings.enterPin": "Entrer le PIN",
    "settings.confirmPin": "Confirmer le PIN",
    "settings.setPin": "Définir le PIN",
    "settings.unlockSettings": "Entrez le PIN pour accéder aux paramètres",
    "settings.parentalControl": "Le contrôle parental est activé",
    "settings.unlock": "Déverrouiller les paramètres",
    "settings.settingsUnlocked": "Paramètres déverrouillés",
    "settings.lockSettings": "Verrouiller les paramètres",
    "settings.insulinRatio": "Ratio insuline/glucides (I:C)",
    "settings.insulinRatioDesc": "1 unité d'insuline couvre {ratio} grammes de glucides",
    "settings.portionSize": "Taille de portion",
    "settings.portionSizeDesc": "Sélectionner la taille de portion typique pour l'estimation des glucides",
    "settings.childPortion": "Portion enfant",
    "settings.adultPortion": "Portion adulte",
    "settings.comments": "Commentaires / Notes",
    "settings.commentsPlaceholder": "Ajoutez des notes ou commentaires sur la gestion de votre diabète...",
    "settings.commentsDesc": "Utilisez cet espace pour les rappels, notes du médecin ou autres informations importantes",
    "settings.invalidPin": "PIN invalide",
    "settings.invalidPinDesc": "Le PIN doit comporter exactement 4 chiffres",
    "settings.pinMismatch": "Les PINs ne correspondent pas",
    "settings.pinMismatchDesc": "Veuillez vous assurer que les deux PINs correspondent",
    "settings.pinSuccess": "PIN défini avec succès",
    "settings.pinSuccessDesc": "Votre PIN de contrôle parental a été créé",
    "settings.accessGranted": "Accès autorisé",
    "settings.accessGrantedDesc": "Bienvenue dans les paramètres",
    "settings.incorrectPin": "PIN incorrect",
    "settings.incorrectPinDesc": "Veuillez réessayer",
    "settings.rereadDisclaimer": "Relire l'avertissement",
    
    // Meal Examples
    "meals.title": "Exemples de repas pour enfants",
    "meals.subtitle": "Repas courants avec estimations de glucides",
    "meals.breakfast": "Petit-déjeuner",
    "meals.lunch": "Déjeuner",
    "meals.dinner": "Dîner",
    "meals.supper": "Souper",
    "meals.disclaimer": "💡 Ce sont des estimations. Vérifiez toujours avec les étiquettes nutritionnelles quand c'est possible.",
    "meals.insulinEstimate": "~{insulin}u d'insuline",
    
    // Meal names
    "meal.pancakes": "Crêpes au sirop",
    "meal.pancakesDesc": "2 crêpes moyennes avec 2 c. à soupe de sirop",
    "meal.cereal": "Céréales au lait",
    "meal.cerealDesc": "1 tasse de céréales avec 1/2 tasse de lait",
    "meal.toast": "Pain grillé à la confiture",
    "meal.toastDesc": "2 tranches de pain grillé avec 1 c. à soupe de confiture",
    "meal.oatmeal": "Gruau à la banane",
    "meal.oatmealDesc": "1 tasse de gruau avec 1 petite banane",
    "meal.waffles": "Gaufres aux fruits",
    "meal.wafflesDesc": "2 gaufres avec 1/2 tasse de baies",
    "meal.bagel": "Bagel au fromage à la crème",
    "meal.bagelDesc": "1 petit bagel avec 2 c. à soupe de fromage à la crème",
    "meal.pbSandwich": "Sandwich au beurre d'arachide",
    "meal.pbSandwichDesc": "2 tranches de pain avec 2 c. à soupe de beurre d'arachide",
    "meal.macCheese": "Macaroni au fromage",
    "meal.macCheeseDesc": "1 tasse de macaroni au fromage préparé",
    "meal.nuggets": "Repas de croquettes de poulet",
    "meal.nuggetsDesc": "6 croquettes avec petites frites",
    "meal.grilledCheese": "Sandwich au fromage grillé",
    "meal.grilledCheeseDesc": "2 tranches de pain avec fromage",
    "meal.pizza": "Part de pizza",
    "meal.pizzaDesc": "1 part de pizza au fromage",
    "meal.turkeyWrap": "Wrap à la dinde",
    "meal.turkeyWrapDesc": "1 tortilla avec dinde et légumes",
    "meal.roastChicken": "Poulet rôti aux légumes",
    "meal.roastChickenDesc": "Poulet cuit au four avec légumes rôtis et petite pomme de terre",
    "meal.meatloaf": "Pain de viande avec accompagnements",
    "meal.meatloafDesc": "Tranche de pain de viande avec haricots verts et purée",
    "meal.stirFry": "Sauté de bœuf",
    "meal.stirFryDesc": "Sauté de bœuf aux légumes sur riz",
    "meal.salmon": "Dîner de saumon cuit",
    "meal.salmonDesc": "Filet de saumon avec brocoli et riz",
    "meal.chickenParm": "Poulet parmigiana",
    "meal.chickenParmDesc": "Poulet pané avec fromage fondu sur spaghetti",
    "meal.porkChop": "Dîner de côtelette de porc",
    "meal.porkChopDesc": "Côtelette de porc grillée avec compote de pommes et maïs",
    "meal.spaghetti": "Spaghetti aux boulettes",
    "meal.spaghettiDesc": "1 tasse de pâtes avec 3 boulettes",
    "meal.chickenRice": "Poulet au riz",
    "meal.chickenRiceDesc": "115g de poulet avec 3/4 tasse de riz",
    "meal.tacos": "Tacos",
    "meal.tacosDesc": "2 tacos mous avec viande et garnitures",
    "meal.fishSticks": "Repas de bâtonnets de poisson",
    "meal.fishSticksDesc": "5 bâtonnets de poisson avec purée",
    "meal.hamburger": "Hamburger avec pain",
    "meal.hamburgerDesc": "1 burger avec pain et petit accompagnement",
    "meal.quesadilla": "Quesadilla au poulet",
    "meal.quesadillaDesc": "1 quesadilla avec fromage et poulet",
    
    // Admin
    "admin.title": "Tableau de bord admin",
    "admin.backToApp": "Retour à l'application",
    "admin.inviteUser": "Inviter un nouvel utilisateur",
    "admin.email": "Email",
    "admin.temporaryPassword": "Mot de passe temporaire",
    "admin.fullName": "Nom complet (optionnel)",
    "admin.minCharacters": "Min 6 caractères",
    "admin.creating": "Création...",
    "admin.createAccount": "Créer un compte utilisateur",
    "admin.users": "Utilisateurs",
    "admin.name": "Nom",
    "admin.role": "Rôle",
    "admin.created": "Créé",
    "admin.actions": "Actions",
    "admin.removeAdmin": "Retirer admin",
    "admin.makeAdmin": "Rendre admin",
    "admin.deleteUser": "Supprimer l'utilisateur",
    "admin.deleteConfirm": "Êtes-vous sûr de vouloir supprimer cet utilisateur? Cette action est irréversible.",
    "admin.cancel": "Annuler",
    "admin.delete": "Supprimer",
    "admin.userCreated": "Utilisateur créé",
    "admin.successInvite": "{email} invité avec succès",
    "admin.userDeleted": "Utilisateur supprimé",
    "admin.userRemoved": "L'utilisateur a été supprimé",
    "admin.adminRoleRemoved": "Rôle admin retiré",
    "admin.adminRoleGranted": "Rôle admin accordé",
    "admin.accessDenied": "Accès refusé",
    "admin.noPermissions": "Vous n'avez pas les permissions d'admin",
    "admin.loading": "Chargement...",
    "admin.status": "Statut",
    "admin.approve": "Approuver",
    "admin.decline": "Refuser",
    "admin.userApproved": "Utilisateur approuvé",
    "admin.userCanLogin": "L'utilisateur peut maintenant se connecter à l'application",
    "admin.userDeclined": "Utilisateur refusé",
    "admin.userDenied": "L'accès utilisateur a été refusé",
    "admin.membershipApplications": "Demandes d'adhésion",
    "admin.pending": "En attente",
    "admin.noPendingApplications": "Aucune demande en attente",
    "admin.applicationMessage": "Message de la demande:",
    "admin.reject": "Rejeter",
    
    // Admin Statistics
    "admin.statistics": "Statistiques",
    "admin.totalUsers": "Total des utilisateurs",
    "admin.appStarts": "Démarrages de l'application",
    "admin.newUsers30Days": "Nouveaux utilisateurs (30 jours)",
    "admin.userGrowth": "Croissance des utilisateurs (30 derniers jours)",
    "admin.applicationApproved": "Demande approuvée",
    "admin.applicationApprovedDesc": "Compte utilisateur créé et e-mail envoyé.",
    "admin.applicationRejected": "Demande rejetée",
    "admin.applicationRejectedDesc": "La demande a été rejetée.",
    "admin.resetEmailSent": "E-mail de réinitialisation envoyé",
    "admin.resetEmailSentDesc": "E-mail de réinitialisation du mot de passe envoyé à {email}",
    
    // Membership Application
    "application.title": "Postuler pour l'adhésion",
    "application.description": "Remplissez le formulaire ci-dessous pour postuler. Vous recevrez un e-mail de confirmation une fois soumis.",
    "application.email": "E-mail",
    "application.whyJoin": "Pourquoi voulez-vous rejoindre?",
    "application.whyJoinPlaceholder": "Parlez-nous un peu de vous et pourquoi vous souhaitez devenir membre...",
    "application.cancel": "Annuler",
    "application.submit": "Soumettre la demande",
    "application.submitting": "Envoi...",
    "application.noAccount": "Vous n'avez pas encore de compte?",
    
    // NotFound
    "notFound.title": "404",
    "notFound.message": "Oups! Page introuvable",
    "notFound.returnHome": "Retour à l'accueil",
  },
  es: {
    // StartPage
    "start.welcome": "¡Bienvenido a CarbSmart!",
    "start.description": "Toma fotos de comidas y obtén estimaciones instantáneas de carbohidratos para ayudar a manejar la diabetes de tu hijo",
    "start.getStarted": "Comenzar",
    "start.selectLanguage": "Seleccionar idioma",
    "start.disclaimerTitle": "Aviso importante",
    "start.disclaimerText": "Esta aplicación utiliza IA para estimar el contenido de carbohidratos de los alimentos a partir de imágenes. Los resultados son solo estimaciones y pueden ser inexactos según cómo se tomen las fotos.\n\nUsa siempre esta herramienta con cuidado: debes comprender los conceptos básicos del conteo de carbohidratos y el cálculo de insulina antes de usarla.\n\nLa aplicación y sus creadores no se responsabilizan de ninguna decisión médica o dietética basada en estos resultados. Confirma siempre con un profesional de la salud en caso de duda.",
    "start.accept": "Entiendo y acepto",
    "start.decline": "Rechazar",
    
    // Main App
    "app.title": "CarbSmart",
    "app.subtitle": "tu contador de carbohidratos",
    "app.analyzing": "Analizando...",
    "app.analyzingDesc": "La IA está examinando tu foto de comida",
    "app.analysisComplete": "¡Análisis completo!",
    "app.analysisCompleteDesc": "Se encontraron {carbs}g de carbohidratos, sugiriendo {insulin} unidades de insulina",
    "app.savedToHistory": "Guardado en historial",
    "app.savedToHistoryDesc": "Tu comida ha sido guardada exitosamente",
    "app.error": "Error",
    "app.errorDesc": "Error al analizar la imagen. Por favor, inténtalo de nuevo.",
    
    // Tabs
    "tabs.capture": "Capturar",
    "tabs.meals": "Comidas",
    "tabs.history": "Historial",
    "tabs.info": "Info",
    "tabs.settings": "Ajustes",
    
    // Auth
    "auth.welcome": "Bienvenido a CarbSmart",
    "auth.welcomeDesc": "Inicia sesión o crea una cuenta para continuar",
    "auth.signIn": "Iniciar sesión",
    "auth.signUp": "Registrarse",
    "auth.admin": "Admin",
    "auth.adminSignIn": "Inicio de sesión de Admin",
    "auth.notAdmin": "No tienes privilegios de admin",
    "auth.email": "Correo electrónico",
    "auth.password": "Contraseña (mín. 6 caracteres)",
    "auth.loading": "Cargando...",
    "auth.signupSuccess": "Cuenta creada",
    "auth.signupSuccessDesc": "Ahora puedes iniciar sesión con tus credenciales",
    "auth.signOut": "Cerrar sesión",
    "auth.forgotPassword": "¿Olvidaste tu contraseña?",
    "auth.resetPassword": "Restablecer contraseña",
    "auth.sendResetLink": "Enviar enlace de restablecimiento",
    "auth.resetEmailSent": "Email de restablecimiento enviado",
    "auth.checkEmail": "Revisa tu correo para el enlace de restablecimiento de contraseña",
    "auth.sending": "Enviando...",
    "auth.cancel": "Cancelar",
    "auth.accountPending": "Cuenta pendiente de aprobación",
    "auth.accountPendingDesc": "Tu cuenta está esperando la aprobación del admin",
    "auth.accountDeclined": "Cuenta rechazada",
    "auth.accountDeclinedDesc": "Tu cuenta ha sido rechazada por un admin",
    "auth.profileError": "No se pudo verificar el estado de la cuenta",
    
    // Camera
    "camera.title": "Capturar comida",
    "camera.takePhoto": "Tomar foto",
    "camera.retake": "Retomar",
    "camera.analyze": "Analizar",
    "camera.error": "Error de cámara",
    "camera.errorDesc": "No se pudo acceder a la cámara. Por favor, verifica los permisos.",
    
    // Results
    "results.title": "Resultados",
    "results.estimatedCarbs": "Carbohidratos estimados",
    "results.totalCarbs": "Total de carbohidratos",
    "results.recommendedInsulin": "Dosis de insulina recomendada",
    "results.insulinNeeded": "Insulina necesaria",
    "results.grams": "gramos",
    "results.units": "unidades",
    "results.carbs": "Carbohidratos",
    "results.basedOnRatio": "Basado en ratio 1:{ratio}",
    "results.fromPhotos": "de {count} fotos",
    "results.addMore": "Más fotos",
    "results.done": "Listo - Calcular y guardar",
    "results.abort": "Abortar",
    "results.viewHistory": "Ver historial",
    "results.newPhoto": "Nueva foto",
    
    // History
    "history.title": "Cálculos recientes",
    "history.noHistory": "Aún no hay historial. ¡Comienza tomando una foto!",
    "history.meals": "comida",
    "history.mealsPlural": "comidas",
    "history.carbs": "carbohidratos",
    "history.insulin": "insulina",
    "history.insulinNeeded": "insulina necesaria",
    "history.today": "Hoy",
    
    // Settings
    "settings.title": "Tus ajustes",
    "settings.setupPin": "Configurar control parental",
    "settings.setupPinDesc": "Crea un PIN de 4 dígitos para proteger tus ajustes",
    "settings.enterPin": "Ingresa el PIN",
    "settings.confirmPin": "Confirma el PIN",
    "settings.setPin": "Establecer PIN",
    "settings.unlockSettings": "Ingresa el PIN para acceder a los ajustes",
    "settings.parentalControl": "El control parental está activado",
    "settings.unlock": "Desbloquear ajustes",
    "settings.settingsUnlocked": "Ajustes desbloqueados",
    "settings.lockSettings": "Bloquear ajustes",
    "settings.insulinRatio": "Ratio insulina/carbohidratos (I:C)",
    "settings.insulinRatioDesc": "1 unidad de insulina cubre {ratio} gramos de carbohidratos",
    "settings.portionSize": "Tamaño de porción",
    "settings.portionSizeDesc": "Seleccione el tamaño de porción típico para la estimación de carbohidratos",
    "settings.childPortion": "Porción infantil",
    "settings.adultPortion": "Porción adulta",
    "settings.comments": "Comentarios / Notas",
    "settings.commentsPlaceholder": "Añade notas o comentarios sobre el manejo de tu diabetes...",
    "settings.commentsDesc": "Usa este espacio para recordatorios, notas del médico u otra información importante",
    "settings.invalidPin": "PIN inválido",
    "settings.invalidPinDesc": "El PIN debe tener exactamente 4 dígitos",
    "settings.pinMismatch": "Los PINs no coinciden",
    "settings.pinMismatchDesc": "Por favor, asegúrate de que ambos PINs coincidan",
    "settings.pinSuccess": "PIN establecido con éxito",
    "settings.pinSuccessDesc": "Tu PIN de control parental ha sido creado",
    "settings.accessGranted": "Acceso concedido",
    "settings.accessGrantedDesc": "Bienvenido a ajustes",
    "settings.incorrectPin": "PIN incorrecto",
    "settings.incorrectPinDesc": "Por favor, inténtalo de nuevo",
    "settings.rereadDisclaimer": "Releer aviso",
    
    // Meal Examples
    "meals.title": "Ejemplos de comidas para niños",
    "meals.subtitle": "Comidas comunes con conteos estimados de carbohidratos",
    "meals.breakfast": "Desayuno",
    "meals.lunch": "Almuerzo",
    "meals.dinner": "Cena",
    "meals.supper": "Cena ligera",
    "meals.disclaimer": "💡 Estas son estimaciones. Siempre verifica con las etiquetas nutricionales cuando sea posible.",
    "meals.insulinEstimate": "~{insulin}u de insulina",
    
    // Meal names
    "meal.pancakes": "Panqueques con jarabe",
    "meal.pancakesDesc": "2 panqueques medianos con 2 cdas de jarabe",
    "meal.cereal": "Cereal con leche",
    "meal.cerealDesc": "1 taza de cereal con 1/2 taza de leche",
    "meal.toast": "Tostada con mermelada",
    "meal.toastDesc": "2 rebanadas de pan tostado con 1 cda de mermelada",
    "meal.oatmeal": "Avena con plátano",
    "meal.oatmealDesc": "1 taza de avena con 1 plátano pequeño",
    "meal.waffles": "Waffles con fruta",
    "meal.wafflesDesc": "2 waffles con 1/2 taza de bayas",
    "meal.bagel": "Bagel con queso crema",
    "meal.bagelDesc": "1 bagel pequeño con 2 cdas de queso crema",
    "meal.pbSandwich": "Sándwich de mantequilla de maní",
    "meal.pbSandwichDesc": "2 rebanadas de pan con 2 cdas de mantequilla de maní",
    "meal.macCheese": "Macarrones con queso",
    "meal.macCheeseDesc": "1 taza de macarrones con queso preparados",
    "meal.nuggets": "Comida de nuggets de pollo",
    "meal.nuggetsDesc": "6 nuggets con papas fritas pequeñas",
    "meal.grilledCheese": "Sándwich de queso a la plancha",
    "meal.grilledCheeseDesc": "2 rebanadas de pan con queso",
    "meal.pizza": "Porción de pizza",
    "meal.pizzaDesc": "1 porción de pizza de queso",
    "meal.turkeyWrap": "Wrap de pavo",
    "meal.turkeyWrapDesc": "1 tortilla con pavo y vegetales",
    "meal.roastChicken": "Pollo asado con vegetales",
    "meal.roastChickenDesc": "Pollo horneado con vegetales asados y papa pequeña",
    "meal.meatloaf": "Pastel de carne con acompañamientos",
    "meal.meatloafDesc": "Porción de pastel de carne con judías verdes y puré",
    "meal.stirFry": "Salteado de carne",
    "meal.stirFryDesc": "Salteado de carne con vegetales sobre arroz",
    "meal.salmon": "Cena de salmón horneado",
    "meal.salmonDesc": "Filete de salmón con brócoli y arroz",
    "meal.chickenParm": "Pollo parmesano",
    "meal.chickenParmDesc": "Pollo empanado con queso derretido sobre espagueti",
    "meal.porkChop": "Cena de chuleta de cerdo",
    "meal.porkChopDesc": "Chuleta de cerdo a la parrilla con puré de manzana y maíz",
    "meal.spaghetti": "Espagueti con albóndigas",
    "meal.spaghettiDesc": "1 taza de pasta con 3 albóndigas",
    "meal.chickenRice": "Pollo con arroz",
    "meal.chickenRiceDesc": "115g de pollo con 3/4 taza de arroz",
    "meal.tacos": "Tacos",
    "meal.tacosDesc": "2 tacos suaves con carne y coberturas",
    "meal.fishSticks": "Comida de palitos de pescado",
    "meal.fishSticksDesc": "5 palitos de pescado con puré",
    "meal.hamburger": "Hamburguesa con pan",
    "meal.hamburgerDesc": "1 hamburguesa con pan y acompañamiento pequeño",
    "meal.quesadilla": "Quesadilla de pollo",
    "meal.quesadillaDesc": "1 quesadilla con queso y pollo",
    
    // Admin
    "admin.title": "Panel de admin",
    "admin.backToApp": "Volver a la aplicación",
    "admin.inviteUser": "Invitar nuevo usuario",
    "admin.email": "Correo electrónico",
    "admin.temporaryPassword": "Contraseña temporal",
    "admin.fullName": "Nombre completo (opcional)",
    "admin.minCharacters": "Mín. 6 caracteres",
    "admin.creating": "Creando...",
    "admin.createAccount": "Crear cuenta de usuario",
    "admin.users": "Usuarios",
    "admin.name": "Nombre",
    "admin.role": "Rol",
    "admin.created": "Creado",
    "admin.actions": "Acciones",
    "admin.removeAdmin": "Quitar admin",
    "admin.makeAdmin": "Hacer admin",
    "admin.deleteUser": "Eliminar usuario",
    "admin.deleteConfirm": "¿Estás seguro de que quieres eliminar este usuario? Esta acción no se puede deshacer.",
    "admin.cancel": "Cancelar",
    "admin.delete": "Eliminar",
    "admin.userCreated": "Usuario creado",
    "admin.successInvite": "Se invitó exitosamente a {email}",
    "admin.userDeleted": "Usuario eliminado",
    "admin.userRemoved": "El usuario ha sido eliminado",
    "admin.adminRoleRemoved": "Rol de admin eliminado",
    "admin.adminRoleGranted": "Rol de admin otorgado",
    "admin.accessDenied": "Acceso denegado",
    "admin.noPermissions": "No tienes permisos de admin",
    "admin.loading": "Cargando...",
    "admin.status": "Estado",
    "admin.approve": "Aprobar",
    "admin.decline": "Rechazar",
    "admin.userApproved": "Usuario aprobado",
    "admin.userCanLogin": "El usuario ahora puede iniciar sesión en la aplicación",
    "admin.userDeclined": "Usuario rechazado",
    "admin.userDenied": "El acceso del usuario ha sido denegado",
    "admin.membershipApplications": "Solicitudes de membresía",
    "admin.pending": "Pendiente",
    "admin.noPendingApplications": "No hay solicitudes pendientes",
    "admin.applicationMessage": "Mensaje de solicitud:",
    "admin.reject": "Rechazar",
    
    // Admin Statistics
    "admin.statistics": "Estadísticas",
    "admin.totalUsers": "Total de usuarios",
    "admin.appStarts": "Inicios de aplicación",
    "admin.newUsers30Days": "Nuevos usuarios (30 días)",
    "admin.userGrowth": "Crecimiento de usuarios (Últimos 30 días)",
    "admin.applicationApproved": "Solicitud aprobada",
    "admin.applicationApprovedDesc": "Cuenta de usuario creada y correo enviado.",
    "admin.applicationRejected": "Solicitud rechazada",
    "admin.applicationRejectedDesc": "La solicitud ha sido rechazada.",
    "admin.resetEmailSent": "Correo de restablecimiento enviado",
    "admin.resetEmailSentDesc": "Correo de restablecimiento de contraseña enviado a {email}",
    
    // Membership Application
    "application.title": "Solicitar membresía",
    "application.description": "Complete el formulario a continuación para solicitar membresía. Recibirá un correo de confirmación una vez enviado.",
    "application.email": "Correo electrónico",
    "application.whyJoin": "¿Por qué quieres unirte?",
    "application.whyJoinPlaceholder": "Cuéntanos un poco sobre ti y por qué te gustaría ser miembro...",
    "application.cancel": "Cancelar",
    "application.submit": "Enviar solicitud",
    "application.submitting": "Enviando...",
    "application.noAccount": "¿Aún no tienes una cuenta?",
    
    // NotFound
    "notFound.title": "404",
    "notFound.message": "¡Ups! Página no encontrada",
    "notFound.returnHome": "Volver al inicio",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        text = text.replace(`{${param}}`, String(value));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
