// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-meal-logs.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_meal_logs_default = defineTool({
  name: "list_meal_logs",
  title: "List meal logs",
  description: "List the signed-in user's recent meal logs (carbs, insulin dose, timestamp).",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max number of logs to return (default 50)."),
    since: z.string().optional().describe("Optional ISO timestamp; only logs created at or after this time are returned.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, since }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("meal_logs").select("id, timestamp, carbs_estimate, insulin_dose, insulin_ratio, created_at").eq("user_id", ctx.getUserId()).order("timestamp", { ascending: false }).limit(limit ?? 50);
    if (since) query = query.gte("timestamp", since);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { logs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-daily-summary.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_daily_summary_default = defineTool2({
  name: "get_daily_summary",
  title: "Get daily carb summary",
  description: "Get total carbs and insulin doses for the signed-in user on a given date (YYYY-MM-DD, UTC). Defaults to today.",
  inputSchema: {
    date: z2.string().optional().describe("Date in YYYY-MM-DD (UTC). Omit for today.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const day = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const start = `${day}T00:00:00.000Z`;
    const end = `${day}T23:59:59.999Z`;
    const { data, error } = await supabaseForUser2(ctx).from("meal_logs").select("carbs_estimate, insulin_dose").eq("user_id", ctx.getUserId()).gte("timestamp", start).lte("timestamp", end);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const totals = (data ?? []).reduce(
      (acc, r) => ({
        carbs: acc.carbs + Number(r.carbs_estimate ?? 0),
        insulin: acc.insulin + Number(r.insulin_dose ?? 0),
        count: acc.count + 1
      }),
      { carbs: 0, insulin: 0, count: 0 }
    );
    const summary = { date: day, ...totals };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool3({
  name: "get_profile",
  title: "Get my profile",
  description: "Get the signed-in user's CarbSmart profile (email, name, insulin ratio, portion size, adjustment %).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("profiles").select("id, email, full_name, insulin_ratio, portion_size, carb_adjustment_percentage, status").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dfgbtsbmgojysixiqnll";
var mcp_default = defineMcp({
  name: "carbsmart-mcp",
  title: "CarbSmart",
  version: "0.1.0",
  instructions: "Tools for CarbSmart \u2014 a personal carb & insulin tracker. Use `list_meal_logs` to browse recent meals, `get_daily_summary` to total carbs/insulin for a day, and `get_profile` for the user's settings. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_meal_logs_default, get_daily_summary_default, get_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
